spring.application.name=GreenCanyonAirBnB
spring.application.ui.title=Automated AirBnB Booking System
# H2 In-Memory Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
debug=true
app.jwt.secret=Wd8+jXIo+wvl7hnW0+7I3PUCRVgt9j8dc2Uf61ZI1oM=
app.jwt.expirationMs=86400000
server.port=8081